/*This file is auto generated by DbEntityGenerator*/
#pragma once

#include <qobject.h>
#include <qvariant.h>
#include <qdatetime.h>
#include <qjsonobject.h>

#include "condition/EntityField.h"

class BangumiDatabase {
    Q_GADGET

    Q_PROPERTY(int id MEMBER id)
    Q_PROPERTY(int bangumiId MEMBER bangumiId)
    Q_PROPERTY(QString title MEMBER title)
    Q_PROPERTY(QString type MEMBER type)
    Q_PROPERTY(QString officialSite MEMBER officialSite)
    Q_PROPERTY(qint64 beginDate MEMBER beginDate)
    Q_PROPERTY(QString sites MEMBER sites)
    Q_PROPERTY(int star MEMBER star)
    Q_PROPERTY(QVariantMap extra MEMBER __extra)

private:
    //
    int id;
    //Bangumi网站数据id
    int bangumiId;
    //番剧名
    QString title;
    //番剧类型
    QString type;
    //官方网站
    QString officialSite;
    //开播时间
    qint64 beginDate;
    //放送网站
    QString sites;
    //标记
    int star;

    QVariantMap __extra;

public:

   BangumiDatabase() {
        id = -1;
   }

    BangumiDatabase(
        const int& bangumiId,
        const QString& title,
        const QString& type,
        const QString& officialSite,
        const qint64& beginDate,
        const QString& sites,
        const int& star
    ) : bangumiId(bangumiId)
    , title(title)
    , type(type)
    , officialSite(officialSite)
    , beginDate(beginDate)
    , sites(sites)
    , star(star)
    {
        id = -1;
    }

public:
    class Fields {
    public:
        EntityField<int> id = EntityField<int>("id", "ir_bangumidatabase");
        EntityField<int> bangumiId = EntityField<int>("bangumi_id", "ir_bangumidatabase");
        EntityField<QString> title = EntityField<QString>("title", "ir_bangumidatabase");
        EntityField<QString> type = EntityField<QString>("type", "ir_bangumidatabase");
        EntityField<QString> officialSite = EntityField<QString>("official_site", "ir_bangumidatabase");
        EntityField<qint64> beginDate = EntityField<qint64>("begin_date", "ir_bangumidatabase");
        EntityField<QString> sites = EntityField<QString>("sites", "ir_bangumidatabase");
        EntityField<int> star = EntityField<int>("star", "ir_bangumidatabase");

    protected:
        void reset(const QString& tbName) {
            id = EntityField<int>("id", tbName);
            bangumiId = EntityField<int>("bangumi_id", tbName);
            title = EntityField<QString>("title", tbName);
            type = EntityField<QString>("type", tbName);
            officialSite = EntityField<QString>("official_site", tbName);
            beginDate = EntityField<qint64>("begin_date", tbName);
            sites = EntityField<QString>("sites", tbName);
            star = EntityField<int>("star", tbName);
        }
    };

    struct Info {
        enum {
            Attach = 1
        };

        static int fieldSize() {
            return 8;
        }

        static QString getTableName() {
            return QStringLiteral("ir_bangumidatabase");
        }

        static QString getSourceName() {
            return getTableName();
        }

        static QStringList getFields() {
            return QStringList()
                << "id"
                << "bangumi_id"
                << "title"
                << "type"
                << "official_site"
                << "begin_date"
                << "sites"
                << "star";
        }

        static QStringList getFieldsWithoutAutoIncrement() {
            return QStringList()
                << "bangumi_id"
                << "title"
                << "type"
                << "official_site"
                << "begin_date"
                << "sites"
                << "star";
        }

        static QStringList getFieldsType() {
            return QStringList() 
                << QStringLiteral("id integer primary key autoincrement")
                << QStringLiteral("bangumi_id integer")
                << QStringLiteral("title text")
                << QStringLiteral("type text")
                << QStringLiteral("official_site text")
                << QStringLiteral("begin_date integer")
                << QStringLiteral("sites text")
                << QStringLiteral("star integer");
        }

        static QStringList getPrimaryKeys() {
            return QStringList() << "id";
        }

        static QList<QStringList> getIndexFields() {
            return QList<QStringList>();
        }

        static QList<QStringList> getUniqueIndexFields() {
            return QList<QStringList>();
        }

        static bool isAutoIncrement(const QString& name) {
            return name == "id";
        }
    };

    struct Tool {
        static QVariantList getValueWithoutAutoIncrement(const BangumiDatabase& entity) {
            return QVariantList()
                << entity.bangumiId
                << entity.title
                << entity.type
                << entity.officialSite
                << entity.beginDate
                << entity.sites
                << entity.star;
        }

        static QVariant getValueByName(const BangumiDatabase& entity, const QString& target) {
            if (target == "id") {
                return entity.id;
            }
            if (target == "bangumi_id") {
                return entity.bangumiId;
            }
            if (target == "title") {
                return entity.title;
            }
            if (target == "type") {
                return entity.type;
            }
            if (target == "official_site") {
                return entity.officialSite;
            }
            if (target == "begin_date") {
                return entity.beginDate;
            }
            if (target == "sites") {
                return entity.sites;
            }
            if (target == "star") {
                return entity.star;
            }
            return entity.__extra.value(target);
        }

        static void bindAutoIncrementId(BangumiDatabase& entity, const QVariant& id) {
            entity.id = id.value<int>();
        }

        static void bindValue(BangumiDatabase& entity, const QString& target, QVariant value) {
            if (target == "id") {
                entity.id = value.value<int>();
            } else if (target == "bangumi_id") {
                entity.bangumiId = value.value<int>();
            } else if (target == "title") {
                entity.title = value.value<QString>();
            } else if (target == "type") {
                entity.type = value.value<QString>();
            } else if (target == "official_site") {
                entity.officialSite = value.value<QString>();
            } else if (target == "begin_date") {
                entity.beginDate = value.value<qint64>();
            } else if (target == "sites") {
                entity.sites = value.value<QString>();
            } else if (target == "star") {
                entity.star = value.value<int>();
            } else {
                entity.__putExtra(target, value);
            }
        }

        static BangumiDatabase fromJson(const QJsonObject& object) {
            BangumiDatabase entity;
            entity.id = object.value("id").toVariant().value<int>();
            entity.bangumiId = object.value("bangumi_id").toVariant().value<int>();
            entity.title = object.value("title").toVariant().value<QString>();
            entity.type = object.value("type").toVariant().value<QString>();
            entity.officialSite = object.value("official_site").toVariant().value<QString>();
            entity.beginDate = object.value("begin_date").toVariant().value<qint64>();
            entity.sites = object.value("sites").toVariant().value<QString>();
            entity.star = object.value("star").toVariant().value<int>();
            return entity;
        }

        static QJsonObject toJson(const BangumiDatabase& entity, QStringList excludeKeys = QStringList()) {
            QJsonObject object;
            object.insert("id", entity.id);
            object.insert("bangumi_id", entity.bangumiId);
            object.insert("title", entity.title);
            object.insert("type", entity.type);
            object.insert("official_site", entity.officialSite);
            object.insert("begin_date", entity.beginDate);
            object.insert("sites", entity.sites);
            object.insert("star", entity.star);

            for (const auto& key : excludeKeys) {
                object.remove(key);
            }
            return object;
        }
    };

public:
    //
    inline void setId(const int& id) {this->id = id;}
    //
    inline int getId() const {return id;}
    //set Bangumi网站数据id
    inline void setBangumiId(const int& bangumiId) {this->bangumiId = bangumiId;}
    //get Bangumi网站数据id
    inline int getBangumiId() const {return bangumiId;}
    //set 番剧名
    inline void setTitle(const QString& title) {this->title = title;}
    //get 番剧名
    inline QString getTitle() const {return title;}
    //set 番剧类型
    inline void setType(const QString& type) {this->type = type;}
    //get 番剧类型
    inline QString getType() const {return type;}
    //set 官方网站
    inline void setOfficialSite(const QString& officialSite) {this->officialSite = officialSite;}
    //get 官方网站
    inline QString getOfficialSite() const {return officialSite;}
    //set 开播时间
    inline void setBeginDate(const qint64& beginDate) {this->beginDate = beginDate;}
    //get 开播时间
    inline qint64 getBeginDate() const {return beginDate;}
    //set 放送网站
    inline void setSites(const QString& sites) {this->sites = sites;}
    //get 放送网站
    inline QString getSites() const {return sites;}
    //set 标记
    inline void setStar(const int& star) {this->star = star;}
    //get 标记
    inline int getStar() const {return star;}
    //set temp data
    inline void __putExtra(const QString& key, const QVariant& extra) {this->__extra.insert(key, extra);}
    //get function select result, like get "as" field result
    inline QVariant __getExtra(const QString& key) const {return __extra.value(key);}
};
typedef QList<BangumiDatabase> BangumiDatabaseList;
Q_DECLARE_METATYPE(BangumiDatabase);