# ----------------------------------------------------
# This file is generated by the DbEntityGenerator.
# ----------------------------------------------------


HEADERS += ./SettingTb.h \
    ./RemarkTb.h \
    ./SubscribeTb.h \
    ./SubscribeGroups.h \
    ./SubscribeGroupItem.h \
    ./BangumiDatabase.h \
    ./SavePathCache.h \
    ./SqliteEntityInclude.h
SOURCES += ./SqliteEntityInclude.cpp
