# ----------------------------------------------------
# This file is generated by the DbEntityGenerator.
# ----------------------------------------------------


HEADERS += ./SettingTb.h \
    ./RemarkTb.h \
    ./SqliteEntityInclude.h
SOURCES += ./SqliteEntityInclude.cpp
