# ----------------------------------------------------
# This file is generated by the DbEntityGenerator.
# ----------------------------------------------------


set(ENTITY_FILE_LIST
    ${CMAKE_CURRENT_LIST_DIR}/SqliteEntityInclude.h
    ${CMAKE_CURRENT_LIST_DIR}/SqliteEntityInclude.cpp

    ${CMAKE_CURRENT_LIST_DIR}/SettingTb.h
    ${CMAKE_CURRENT_LIST_DIR}/RemarkTb.h
    ${CMAKE_CURRENT_LIST_DIR}/SubscribeTb.h
    ${CMAKE_CURRENT_LIST_DIR}/SubscribeGroups.h
    ${CMAKE_CURRENT_LIST_DIR}/SubscribeGroupItem.h
    ${CMAKE_CURRENT_LIST_DIR}/BangumiDatabase.h
)