/*This file is auto generated by DbEntityGenerator*/
#pragma once

#include <qobject.h>
#include <qvariant.h>
#include <qdatetime.h>
#include <qjsonobject.h>

#include "condition/EntityField.h"

class RemarkTb {
private:
    //已下载链接
    QString sourceLink;

    QHash<QString, QVariant> __extra;

public:

   RemarkTb() {
   }

    RemarkTb(
        const QString& sourceLink
    ) : sourceLink(sourceLink)
    {
    }

public:
    class Fields {
    public:
        EntityField<QString> sourceLink = EntityField<QString>("source_link", "ir_remarktb");

    protected:
        void reset(const QString& tbName) {
            sourceLink = EntityField<QString>("source_link", tbName);
        }
    };

    struct Info {
        enum {
            Attach = 1
        };

        static int fieldSize() {
            return 1;
        }

        static QString getTableName() {
            return QStringLiteral("ir_remarktb");
        }

        static QString getSourceName() {
            return getTableName();
        }

        static QStringList getFields() {
            return QStringList()
                << "source_link";
        }

        static QStringList getFieldsWithoutAutoIncrement() {
            return QStringList()
                << "source_link";
        }

        static QStringList getFieldsType() {
            return QStringList() 
                << QStringLiteral("source_link text");
        }

        static QStringList getPrimaryKeys() {
            return QStringList();
        }

        static QList<QStringList> getIndexFields() {
            return QList<QStringList>();
        }

        static QList<QStringList> getUniqueIndexFields() {
            return QList<QStringList>();
        }

        static bool isAutoIncrement(const QString& name) {
            Q_UNUSED(name);
            return false;
        }
    };

    struct Tool {
        static QVariantList getValueWithoutAutoIncrement(const RemarkTb& entity) {
            return QVariantList()
                << entity.sourceLink;
        }

        static QVariant getValueByName(const RemarkTb& entity, const QString& target) {
            if (target == "source_link") {
                return entity.sourceLink;
            }
            return entity.__extra.value(target);
        }

        static void bindAutoIncrementId(RemarkTb& entity, const QVariant& id) {
            Q_UNUSED(entity);
            Q_UNUSED(id);
        }

        static void bindValue(RemarkTb& entity, const QString& target, QVariant value) {
            if (target == "source_link") {
                entity.sourceLink = value.value<QString>();
            } else {
                entity.__putExtra(target, value);
            }
        }

        static RemarkTb fromJson(const QJsonObject& object) {
            RemarkTb entity;
            entity.sourceLink = object.value("source_link").toVariant().value<QString>();
            return entity;
        }

        static QJsonObject toJson(const RemarkTb& entity, QStringList excludeKeys = QStringList()) {
            QJsonObject object;
            object.insert("source_link", entity.sourceLink);

            for (const auto& key : excludeKeys) {
                object.remove(key);
            }
            return object;
        }
    };

public:
    //set 已下载链接
    inline void setSourceLink(const QString& sourceLink) {this->sourceLink = sourceLink;}
    //get 已下载链接
    inline QString getSourceLink() const {return sourceLink;}
    //set temp data
    inline void __putExtra(const QString& key, const QVariant& extra) {this->__extra.insert(key, extra);}
    //get function select result, like get "as" field result
    inline QVariant __getExtra(const QString& key) const {return __extra.value(key);}
};
typedef QList<RemarkTb> RemarkTbList;
Q_DECLARE_METATYPE(RemarkTb);