/*This file is auto generated by DbEntityGenerator*/
#pragma once

#include <qobject.h>
#include <qvariant.h>
#include <qdatetime.h>
#include <qjsonobject.h>

#include "condition/EntityField.h"

class SavePathCache {
    
private:
    //番剧id
    int bangumiId;
    //保存的文件路径
    QString savePath;
    //缓存路径时间
    qint64 createTime;

    QVariantMap __extra;

public:

   SavePathCache() {
   }

    SavePathCache(
        const int& bangumiId,
        const QString& savePath,
        const qint64& createTime
    ) : bangumiId(bangumiId)
    , savePath(savePath)
    , createTime(createTime)
    {
    }

public:
    class Fields {
    public:
        EntityField<int> bangumiId = EntityField<int>("bangumi_id", "ir_savepathcache");
        EntityField<QString> savePath = EntityField<QString>("save_path", "ir_savepathcache");
        EntityField<qint64> createTime = EntityField<qint64>("create_time", "ir_savepathcache");

    protected:
        void reset(const QString& tbName) {
            bangumiId = EntityField<int>("bangumi_id", tbName);
            savePath = EntityField<QString>("save_path", tbName);
            createTime = EntityField<qint64>("create_time", tbName);
        }
    };

    struct Info {
        enum {
            Attach = 1
        };

        static int fieldSize() {
            return 3;
        }

        static QString getTableName() {
            return QStringLiteral("ir_savepathcache");
        }

        static QString getSourceName() {
            return getTableName();
        }

        static QStringList getFields() {
            return QStringList()
                << "bangumi_id"
                << "save_path"
                << "create_time";
        }

        static QStringList getFieldsWithoutAutoIncrement() {
            return QStringList()
                << "bangumi_id"
                << "save_path"
                << "create_time";
        }

        static QStringList getFieldsType() {
            return QStringList() 
                << QStringLiteral("bangumi_id integer not null unique")
                << QStringLiteral("save_path text")
                << QStringLiteral("create_time integer");
        }

        static QStringList getPrimaryKeys() {
            return QStringList();
        }

        static QList<QStringList> getIndexFields() {
            return QList<QStringList>();
        }

        static QList<QStringList> getUniqueIndexFields() {
            return QList<QStringList>();
        }

        static bool isAutoIncrement(const QString& name) {
            Q_UNUSED(name);
            return false;
        }
    };

    struct Tool {
        static QVariantList getValueWithoutAutoIncrement(const SavePathCache& entity) {
            return QVariantList()
                << entity.bangumiId
                << entity.savePath
                << entity.createTime;
        }

        static QVariant getValueByName(const SavePathCache& entity, const QString& target) {
            if (target == "bangumi_id") {
                return entity.bangumiId;
            }
            if (target == "save_path") {
                return entity.savePath;
            }
            if (target == "create_time") {
                return entity.createTime;
            }
            return entity.__extra.value(target);
        }

        static void bindAutoIncrementId(SavePathCache& entity, const QVariant& id) {
            Q_UNUSED(entity);
            Q_UNUSED(id);
        }

        static void bindValue(SavePathCache& entity, const QString& target, QVariant value) {
            if (target == "bangumi_id") {
                entity.bangumiId = value.value<int>();
            } else if (target == "save_path") {
                entity.savePath = value.value<QString>();
            } else if (target == "create_time") {
                entity.createTime = value.value<qint64>();
            } else {
                entity.__putExtra(target, value);
            }
        }

        static SavePathCache fromJson(const QJsonObject& object) {
            SavePathCache entity;
            entity.bangumiId = object.value("bangumi_id").toVariant().value<int>();
            entity.savePath = object.value("save_path").toVariant().value<QString>();
            entity.createTime = object.value("create_time").toVariant().value<qint64>();
            return entity;
        }

        static QJsonObject toJson(const SavePathCache& entity, QStringList excludeKeys = QStringList()) {
            QJsonObject object;
            object.insert("bangumi_id", entity.bangumiId);
            object.insert("save_path", entity.savePath);
            object.insert("create_time", entity.createTime);

            for (const auto& key : excludeKeys) {
                object.remove(key);
            }
            return object;
        }
    };

public:
    //set 番剧id
    inline void setBangumiId(const int& bangumiId) {this->bangumiId = bangumiId;}
    //get 番剧id
    inline int getBangumiId() const {return bangumiId;}
    //set 保存的文件路径
    inline void setSavePath(const QString& savePath) {this->savePath = savePath;}
    //get 保存的文件路径
    inline QString getSavePath() const {return savePath;}
    //set 缓存路径时间
    inline void setCreateTime(const qint64& createTime) {this->createTime = createTime;}
    //get 缓存路径时间
    inline qint64 getCreateTime() const {return createTime;}
    //set temp data
    inline void __putExtra(const QString& key, const QVariant& extra) {this->__extra.insert(key, extra);}
    //get function select result, like get "as" field result
    inline QVariant __getExtra(const QString& key) const {return __extra.value(key);}
};
typedef QList<SavePathCache> SavePathCacheList;
