/*This file is auto generated by DbEntityGenerator*/
#pragma once

#include <qobject.h>
#include <qvariant.h>
#include <qdatetime.h>
#include <qjsonobject.h>

#include "condition/EntityField.h"

class SettingTb {
private:
    //key
    QString name;
    //自定义数据类型
    QVariant data;

    QHash<QString, QVariant> __extra;

public:

   SettingTb() {
   }

    SettingTb(
        const QString& name,
        const QVariant& data
    ) : name(name)
    , data(data)
    {
    }

public:
    class Fields {
    public:
        EntityField<QString> name = EntityField<QString>("name", "ir_settingtb");
        EntityField<QVariant> data = EntityField<QVariant>("data", "ir_settingtb");

    protected:
        void reset(const QString& tbName) {
            name = EntityField<QString>("name", tbName);
            data = EntityField<QVariant>("data", tbName);
        }
    };

    struct Info {
        enum {
            Attach = 1
        };

        static int fieldSize() {
            return 2;
        }

        static QString getTableName() {
            return QStringLiteral("ir_settingtb");
        }

        static QString getSourceName() {
            return getTableName();
        }

        static QStringList getFields() {
            return QStringList()
                << "name"
                << "data";
        }

        static QStringList getFieldsWithoutAutoIncrement() {
            return QStringList()
                << "name"
                << "data";
        }

        static QStringList getFieldsType() {
            return QStringList() 
                << QStringLiteral("name text not null unique")
                << QStringLiteral("data blob");
        }

        static QStringList getPrimaryKeys() {
            return QStringList();
        }

        static QList<QStringList> getIndexFields() {
            return QList<QStringList>();
        }

        static QList<QStringList> getUniqueIndexFields() {
            return QList<QStringList>();
        }

        static bool isAutoIncrement(const QString& name) {
            Q_UNUSED(name);
            return false;
        }
    };

    struct Tool {
        static QVariantList getValueWithoutAutoIncrement(const SettingTb& entity) {
            return QVariantList()
                << entity.name
                << entity.data;
        }

        static QVariant getValueByName(const SettingTb& entity, const QString& target) {
            if (target == "name") {
                return entity.name;
            }
            if (target == "data") {
                return entity.data;
            }
            return entity.__extra.value(target);
        }

        static void bindAutoIncrementId(SettingTb& entity, const QVariant& id) {
            Q_UNUSED(entity);
            Q_UNUSED(id);
        }

        static void bindValue(SettingTb& entity, const QString& target, QVariant value) {
            if (target == "name") {
                entity.name = value.value<QString>();
            } else if (target == "data") {
                entity.data = value.value<QVariant>();
            } else {
                entity.__putExtra(target, value);
            }
        }

        static SettingTb fromJson(const QJsonObject& object) {
            SettingTb entity;
            entity.name = object.value("name").toVariant().value<QString>();
            entity.data = object.value("data");
            return entity;
        }

        static QJsonObject toJson(const SettingTb& entity, QStringList excludeKeys = QStringList()) {
            QJsonObject object;
            object.insert("name", entity.name);
            object.insert("data", QJsonValue::fromVariant(entity.data));

            for (const auto& key : excludeKeys) {
                object.remove(key);
            }
            return object;
        }
    };

public:
    //set key
    inline void setName(const QString& name) {this->name = name;}
    //get key
    inline QString getName() const {return name;}
    //set 自定义数据类型
    inline void setData(const QVariant& data) {this->data = data;}
    //get 自定义数据类型
    inline QVariant getData() const {return data;}
    //set temp data
    inline void __putExtra(const QString& key, const QVariant& extra) {this->__extra.insert(key, extra);}
    //get function select result, like get "as" field result
    inline QVariant __getExtra(const QString& key) const {return __extra.value(key);}
};
typedef QList<SettingTb> SettingTbList;
Q_DECLARE_METATYPE(SettingTb);