/*This file is auto generated by DbEntityGenerator*/
#pragma once

#include <qobject.h>
#include <qvariant.h>
#include <qdatetime.h>
#include <qjsonobject.h>

#include "condition/EntityField.h"

class SubscribeGroupItem {
    Q_GADGET

    Q_PROPERTY(int id MEMBER id)
    Q_PROPERTY(int groupId MEMBER groupId)
    Q_PROPERTY(QString sourceLink MEMBER sourceLink)
    Q_PROPERTY(int newItem MEMBER newItem)
    Q_PROPERTY(QVariantMap extra MEMBER __extra)

private:
    //
    int id;
    //字幕组订阅id
    int groupId;
    //字幕组订阅下的种子链接
    QString sourceLink;
    //是否是new状态
    int newItem;

    QVariantMap __extra;

public:

   SubscribeGroupItem() {
        id = -1;
        newItem = 1;
   }

    SubscribeGroupItem(
        const int& groupId,
        const QString& sourceLink,
        const int& newItem
    ) : groupId(groupId)
    , sourceLink(sourceLink)
    , newItem(newItem)
    {
        id = -1;
    }

    SubscribeGroupItem(
        const int& groupId,
        const QString& sourceLink
    ) : groupId(groupId)
    , sourceLink(sourceLink)
    {
        id = -1;
        newItem = 1;
    }

public:
    class Fields {
    public:
        EntityField<int> id = EntityField<int>("id", "ir_subscribegroupitem");
        EntityField<int> groupId = EntityField<int>("group_id", "ir_subscribegroupitem");
        EntityField<QString> sourceLink = EntityField<QString>("source_link", "ir_subscribegroupitem");
        EntityField<int> newItem = EntityField<int>("new_item", "ir_subscribegroupitem");

    protected:
        void reset(const QString& tbName) {
            id = EntityField<int>("id", tbName);
            groupId = EntityField<int>("group_id", tbName);
            sourceLink = EntityField<QString>("source_link", tbName);
            newItem = EntityField<int>("new_item", tbName);
        }
    };

    struct Info {
        enum {
            Attach = 1
        };

        static int fieldSize() {
            return 4;
        }

        static QString getTableName() {
            return QStringLiteral("ir_subscribegroupitem");
        }

        static QString getSourceName() {
            return getTableName();
        }

        static QStringList getFields() {
            return QStringList()
                << "id"
                << "group_id"
                << "source_link"
                << "new_item";
        }

        static QStringList getFieldsWithoutAutoIncrement() {
            return QStringList()
                << "group_id"
                << "source_link"
                << "new_item";
        }

        static QStringList getFieldsType() {
            return QStringList() 
                << QStringLiteral("id integer primary key autoincrement")
                << QStringLiteral("group_id integer")
                << QStringLiteral("source_link text")
                << QStringLiteral("new_item integer null default 1");
        }

        static QStringList getPrimaryKeys() {
            return QStringList() << "id";
        }

        static QList<QStringList> getIndexFields() {
            return QList<QStringList>();
        }

        static QList<QStringList> getUniqueIndexFields() {
            return QList<QStringList>();
        }

        static bool isAutoIncrement(const QString& name) {
            return name == "id";
        }
    };

    struct Tool {
        static QVariantList getValueWithoutAutoIncrement(const SubscribeGroupItem& entity) {
            return QVariantList()
                << entity.groupId
                << entity.sourceLink
                << entity.newItem;
        }

        static QVariant getValueByName(const SubscribeGroupItem& entity, const QString& target) {
            if (target == "id") {
                return entity.id;
            }
            if (target == "group_id") {
                return entity.groupId;
            }
            if (target == "source_link") {
                return entity.sourceLink;
            }
            if (target == "new_item") {
                return entity.newItem;
            }
            return entity.__extra.value(target);
        }

        static void bindAutoIncrementId(SubscribeGroupItem& entity, const QVariant& id) {
            entity.id = id.value<int>();
        }

        static void bindValue(SubscribeGroupItem& entity, const QString& target, QVariant value) {
            if (target == "id") {
                entity.id = value.value<int>();
            } else if (target == "group_id") {
                entity.groupId = value.value<int>();
            } else if (target == "source_link") {
                entity.sourceLink = value.value<QString>();
            } else if (target == "new_item") {
                entity.newItem = value.value<int>();
            } else {
                entity.__putExtra(target, value);
            }
        }

        static SubscribeGroupItem fromJson(const QJsonObject& object) {
            SubscribeGroupItem entity;
            entity.id = object.value("id").toVariant().value<int>();
            entity.groupId = object.value("group_id").toVariant().value<int>();
            entity.sourceLink = object.value("source_link").toVariant().value<QString>();
            entity.newItem = object.value("new_item").toVariant().value<int>();
            return entity;
        }

        static QJsonObject toJson(const SubscribeGroupItem& entity, QStringList excludeKeys = QStringList()) {
            QJsonObject object;
            object.insert("id", entity.id);
            object.insert("group_id", entity.groupId);
            object.insert("source_link", entity.sourceLink);
            object.insert("new_item", entity.newItem);

            for (const auto& key : excludeKeys) {
                object.remove(key);
            }
            return object;
        }
    };

public:
    //
    inline void setId(const int& id) {this->id = id;}
    //
    inline int getId() const {return id;}
    //set 字幕组订阅id
    inline void setGroupId(const int& groupId) {this->groupId = groupId;}
    //get 字幕组订阅id
    inline int getGroupId() const {return groupId;}
    //set 字幕组订阅下的种子链接
    inline void setSourceLink(const QString& sourceLink) {this->sourceLink = sourceLink;}
    //get 字幕组订阅下的种子链接
    inline QString getSourceLink() const {return sourceLink;}
    //set 是否是new状态
    inline void setNewItem(const int& newItem) {this->newItem = newItem;}
    //get 是否是new状态
    inline int getNewItem() const {return newItem;}
    //set temp data
    inline void __putExtra(const QString& key, const QVariant& extra) {this->__extra.insert(key, extra);}
    //get function select result, like get "as" field result
    inline QVariant __getExtra(const QString& key) const {return __extra.value(key);}
};
typedef QList<SubscribeGroupItem> SubscribeGroupItemList;
Q_DECLARE_METATYPE(SubscribeGroupItem);