/*This file is auto generated by DbEntityGenerator*/
#pragma once

#include <qobject.h>
#include <qvariant.h>
#include <qdatetime.h>
#include <qjsonobject.h>

#include "condition/EntityField.h"

class SubscribeTb {
    Q_GADGET

    Q_PROPERTY(int id MEMBER id)
    Q_PROPERTY(int bangumiId MEMBER bangumiId)
    Q_PROPERTY(QString title MEMBER title)
    Q_PROPERTY(QString rssLink MEMBER rssLink)
    Q_PROPERTY(QVariantMap extra MEMBER __extra)

private:
    //
    int id;
    //番剧链接id
    int bangumiId;
    //番剧名
    QString title;
    //Rss订阅地址
    QString rssLink;

    QVariantMap __extra;

public:

   SubscribeTb() {
        id = -1;
   }

    SubscribeTb(
        const int& bangumiId,
        const QString& title,
        const QString& rssLink
    ) : bangumiId(bangumiId)
    , title(title)
    , rssLink(rssLink)
    {
        id = -1;
    }

public:
    class Fields {
    public:
        EntityField<int> id = EntityField<int>("id", "ir_subscribetb");
        EntityField<int> bangumiId = EntityField<int>("bangumi_id", "ir_subscribetb");
        EntityField<QString> title = EntityField<QString>("title", "ir_subscribetb");
        EntityField<QString> rssLink = EntityField<QString>("rss_link", "ir_subscribetb");

    protected:
        void reset(const QString& tbName) {
            id = EntityField<int>("id", tbName);
            bangumiId = EntityField<int>("bangumi_id", tbName);
            title = EntityField<QString>("title", tbName);
            rssLink = EntityField<QString>("rss_link", tbName);
        }
    };

    struct Info {
        enum {
            Attach = 1
        };

        static int fieldSize() {
            return 4;
        }

        static QString getTableName() {
            return QStringLiteral("ir_subscribetb");
        }

        static QString getSourceName() {
            return getTableName();
        }

        static QStringList getFields() {
            return QStringList()
                << "id"
                << "bangumi_id"
                << "title"
                << "rss_link";
        }

        static QStringList getFieldsWithoutAutoIncrement() {
            return QStringList()
                << "bangumi_id"
                << "title"
                << "rss_link";
        }

        static QStringList getFieldsType() {
            return QStringList() 
                << QStringLiteral("id integer primary key autoincrement")
                << QStringLiteral("bangumi_id integer")
                << QStringLiteral("title text")
                << QStringLiteral("rss_link text not null");
        }

        static QStringList getPrimaryKeys() {
            return QStringList() << "id";
        }

        static QList<QStringList> getIndexFields() {
            return QList<QStringList>();
        }

        static QList<QStringList> getUniqueIndexFields() {
            return QList<QStringList>();
        }

        static bool isAutoIncrement(const QString& name) {
            return name == "id";
        }
    };

    struct Tool {
        static QVariantList getValueWithoutAutoIncrement(const SubscribeTb& entity) {
            return QVariantList()
                << entity.bangumiId
                << entity.title
                << entity.rssLink;
        }

        static QVariant getValueByName(const SubscribeTb& entity, const QString& target) {
            if (target == "id") {
                return entity.id;
            }
            if (target == "bangumi_id") {
                return entity.bangumiId;
            }
            if (target == "title") {
                return entity.title;
            }
            if (target == "rss_link") {
                return entity.rssLink;
            }
            return entity.__extra.value(target);
        }

        static void bindAutoIncrementId(SubscribeTb& entity, const QVariant& id) {
            entity.id = id.value<int>();
        }

        static void bindValue(SubscribeTb& entity, const QString& target, QVariant value) {
            if (target == "id") {
                entity.id = value.value<int>();
            } else if (target == "bangumi_id") {
                entity.bangumiId = value.value<int>();
            } else if (target == "title") {
                entity.title = value.value<QString>();
            } else if (target == "rss_link") {
                entity.rssLink = value.value<QString>();
            } else {
                entity.__putExtra(target, value);
            }
        }

        static SubscribeTb fromJson(const QJsonObject& object) {
            SubscribeTb entity;
            entity.id = object.value("id").toVariant().value<int>();
            entity.bangumiId = object.value("bangumi_id").toVariant().value<int>();
            entity.title = object.value("title").toVariant().value<QString>();
            entity.rssLink = object.value("rss_link").toVariant().value<QString>();
            return entity;
        }

        static QJsonObject toJson(const SubscribeTb& entity, QStringList excludeKeys = QStringList()) {
            QJsonObject object;
            object.insert("id", entity.id);
            object.insert("bangumi_id", entity.bangumiId);
            object.insert("title", entity.title);
            object.insert("rss_link", entity.rssLink);

            for (const auto& key : excludeKeys) {
                object.remove(key);
            }
            return object;
        }
    };

public:
    //
    inline void setId(const int& id) {this->id = id;}
    //
    inline int getId() const {return id;}
    //set 番剧链接id
    inline void setBangumiId(const int& bangumiId) {this->bangumiId = bangumiId;}
    //get 番剧链接id
    inline int getBangumiId() const {return bangumiId;}
    //set 番剧名
    inline void setTitle(const QString& title) {this->title = title;}
    //get 番剧名
    inline QString getTitle() const {return title;}
    //set Rss订阅地址
    inline void setRssLink(const QString& rssLink) {this->rssLink = rssLink;}
    //get Rss订阅地址
    inline QString getRssLink() const {return rssLink;}
    //set temp data
    inline void __putExtra(const QString& key, const QVariant& extra) {this->__extra.insert(key, extra);}
    //get function select result, like get "as" field result
    inline QVariant __getExtra(const QString& key) const {return __extra.value(key);}
};
typedef QList<SubscribeTb> SubscribeTbList;
Q_DECLARE_METATYPE(SubscribeTb);