/*This file is auto generated by DbEntityGenerator*/
#pragma once

#include <qobject.h>
#include <qvariant.h>
#include <qdatetime.h>
#include <qjsonobject.h>

#include "condition/EntityField.h"

class SubscribeGroups {
    Q_GADGET

    Q_PROPERTY(int id MEMBER id)
    Q_PROPERTY(int bangumiId MEMBER bangumiId)
    Q_PROPERTY(QString groupName MEMBER groupName)
    Q_PROPERTY(QString keywords MEMBER keywords)
    Q_PROPERTY(QVariantMap extra MEMBER __extra)

private:
    //
    int id;
    //番剧链接id
    int bangumiId;
    //字幕组
    QString groupName;
    //筛选关键字
    QString keywords;

    QVariantMap __extra;

public:

   SubscribeGroups() {
        id = -1;
   }

    SubscribeGroups(
        const int& bangumiId,
        const QString& groupName,
        const QString& keywords
    ) : bangumiId(bangumiId)
    , groupName(groupName)
    , keywords(keywords)
    {
        id = -1;
    }

public:
    class Fields {
    public:
        EntityField<int> id = EntityField<int>("id", "ir_subscribegroups");
        EntityField<int> bangumiId = EntityField<int>("bangumi_id", "ir_subscribegroups");
        EntityField<QString> groupName = EntityField<QString>("group_name", "ir_subscribegroups");
        EntityField<QString> keywords = EntityField<QString>("keywords", "ir_subscribegroups");

    protected:
        void reset(const QString& tbName) {
            id = EntityField<int>("id", tbName);
            bangumiId = EntityField<int>("bangumi_id", tbName);
            groupName = EntityField<QString>("group_name", tbName);
            keywords = EntityField<QString>("keywords", tbName);
        }
    };

    struct Info {
        enum {
            Attach = 1
        };

        static int fieldSize() {
            return 4;
        }

        static QString getTableName() {
            return QStringLiteral("ir_subscribegroups");
        }

        static QString getSourceName() {
            return getTableName();
        }

        static QStringList getFields() {
            return QStringList()
                << "id"
                << "bangumi_id"
                << "group_name"
                << "keywords";
        }

        static QStringList getFieldsWithoutAutoIncrement() {
            return QStringList()
                << "bangumi_id"
                << "group_name"
                << "keywords";
        }

        static QStringList getFieldsType() {
            return QStringList() 
                << QStringLiteral("id integer primary key autoincrement")
                << QStringLiteral("bangumi_id integer")
                << QStringLiteral("group_name text")
                << QStringLiteral("keywords text");
        }

        static QStringList getPrimaryKeys() {
            return QStringList() << "id";
        }

        static QList<QStringList> getIndexFields() {
            return QList<QStringList>();
        }

        static QList<QStringList> getUniqueIndexFields() {
            return QList<QStringList>();
        }

        static bool isAutoIncrement(const QString& name) {
            return name == "id";
        }
    };

    struct Tool {
        static QVariantList getValueWithoutAutoIncrement(const SubscribeGroups& entity) {
            return QVariantList()
                << entity.bangumiId
                << entity.groupName
                << entity.keywords;
        }

        static QVariant getValueByName(const SubscribeGroups& entity, const QString& target) {
            if (target == "id") {
                return entity.id;
            }
            if (target == "bangumi_id") {
                return entity.bangumiId;
            }
            if (target == "group_name") {
                return entity.groupName;
            }
            if (target == "keywords") {
                return entity.keywords;
            }
            return entity.__extra.value(target);
        }

        static void bindAutoIncrementId(SubscribeGroups& entity, const QVariant& id) {
            entity.id = id.value<int>();
        }

        static void bindValue(SubscribeGroups& entity, const QString& target, QVariant value) {
            if (target == "id") {
                entity.id = value.value<int>();
            } else if (target == "bangumi_id") {
                entity.bangumiId = value.value<int>();
            } else if (target == "group_name") {
                entity.groupName = value.value<QString>();
            } else if (target == "keywords") {
                entity.keywords = value.value<QString>();
            } else {
                entity.__putExtra(target, value);
            }
        }

        static SubscribeGroups fromJson(const QJsonObject& object) {
            SubscribeGroups entity;
            entity.id = object.value("id").toVariant().value<int>();
            entity.bangumiId = object.value("bangumi_id").toVariant().value<int>();
            entity.groupName = object.value("group_name").toVariant().value<QString>();
            entity.keywords = object.value("keywords").toVariant().value<QString>();
            return entity;
        }

        static QJsonObject toJson(const SubscribeGroups& entity, QStringList excludeKeys = QStringList()) {
            QJsonObject object;
            object.insert("id", entity.id);
            object.insert("bangumi_id", entity.bangumiId);
            object.insert("group_name", entity.groupName);
            object.insert("keywords", entity.keywords);

            for (const auto& key : excludeKeys) {
                object.remove(key);
            }
            return object;
        }
    };

public:
    //
    inline void setId(const int& id) {this->id = id;}
    //
    inline int getId() const {return id;}
    //set 番剧链接id
    inline void setBangumiId(const int& bangumiId) {this->bangumiId = bangumiId;}
    //get 番剧链接id
    inline int getBangumiId() const {return bangumiId;}
    //set 字幕组
    inline void setGroupName(const QString& groupName) {this->groupName = groupName;}
    //get 字幕组
    inline QString getGroupName() const {return groupName;}
    //set 筛选关键字
    inline void setKeywords(const QString& keywords) {this->keywords = keywords;}
    //get 筛选关键字
    inline QString getKeywords() const {return keywords;}
    //set temp data
    inline void __putExtra(const QString& key, const QVariant& extra) {this->__extra.insert(key, extra);}
    //get function select result, like get "as" field result
    inline QVariant __getExtra(const QString& key) const {return __extra.value(key);}
};
typedef QList<SubscribeGroups> SubscribeGroupsList;
Q_DECLARE_METATYPE(SubscribeGroups);